services:
  - type: web
    name: html-to-pdf-converter
    env: docker
    region: frankfurt  # Of oregon/singapore
    plan: starter  # Of free voor testing
    dockerfilePath: ./Dockerfile
    dockerContext: .
    
    # Health check
    healthCheckPath: /health
    
    # Environment variables
    envVars:
      - key: RENDER_EXTERNAL_URL
        sync: false
        # Dit wordt automatisch ingesteld door Render
      
    # Disks voor persistent storage
    disks:
      - name: pdf-storage
        mountPath: /app/static/output
        sizeGB: 1
      - name: word-storage
        mountPath: /app/static/word_output
        sizeGB: 1
    
    # Auto-deploy bij push
    autoDeploy: true
